### ISSUE TITLE
Helper functions :)

### ISSUE THREAD

**Issue by MarcelloTheArcane** [thesephist/tabloid#6]
Hey! This is fun 😃 

I made a quick repo with some helper functions: https://github.com/marcellothearcane/tabloid-samples

**Comment by MarcelloTheArcane** [comment]
Is there no memory stack or array operations?

**Comment by thesephist** [comment]
Hey, neat project! haha. Thanks for sharing.

Yeah, Tabloid doesn't have any composite data structures like arrays or stacks, because it was a quick hack. I think in theory you should be able to emulate stacks with closures (by closing over variables in nested scopes?) but there's a chance you'll hit the JavaScript recursion limit doing that too much.

If you do want to add array support, feel free to fork. It would just have added a lot to the language, so I never bothered.
